### ISSUE TITLE
I can't use the power cord to work after the injection.

### ISSUE THREAD

**Issue by xhyrom** [powercord-org/powercord#524]
VM624 C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\managers\apis.js:17 [Powercord:API] An error occurred while initializing "i18n"! TypeError: Cannot read property '_proxyContext' of null
    at I18nAPI.addPowercordStrings (C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\apis\i18n.js:29:24)
    at I18nAPI.loadStrings (C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\apis\i18n.js:51:10)
    at C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\apis\i18n.js:39:49
    at Array.forEach (<anonymous>)
    at I18nAPI.loadAllStrings (C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\apis\i18n.js:39:26)
    at new I18nAPI (C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\apis\i18n.js:11:10)
    at APIManager.mount (C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\managers\apis.js:14:28)
    at C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\managers\apis.js:38:33
    at Array.forEach (<anonymous>)
    at APIManager.startAPIs (C:\Users\hyrob\Documents\PowerCord\powercord\src\Powercord\managers\apis.js:38:8)

![obrázok](https://user-images.githubusercontent.com/56601352/125240366-4ef78100-e2ea-11eb-9069-16706e4e67b3.png)

**Comment by mixcoac** [comment]
Read #known-issues before opening an issue.

Waiting on this to get closed

**Comment by doggybootsy** [comment]
**Powercord injects, but no plugins or settings**
It seems that a Discord update has broken a few of Powercord's coremods - as such plugins, etc. will not be functional for the time being. As is usual, Powercord developers will work on a fix when they are able. There is no eta.

Quoted from the known issue channel

**Comment by cyyynthia** [comment]
Fixed in ea54ca0
