### ISSUE TITLE
Powercord doesn't launch (JS error)

### ISSUE THREAD

**Issue by kujonello79** [powercord-org/powercord#618]
**Describe the bug**
Powercord doesn't work when installed on Arch Linux and distros based on it from AUR.

**To Reproduce**
Install from [AUR](https://aur.archlinux.org/packages/powercord-electron-git)
Run with command _powercord_

**Expected behavior**
Powercord launches without any errors.

**Desktop (please complete the following information):**
 - OS: Artix GNU/Linux [OpenRC]
 - Powercord version: current from [AUR](https://aur.archlinux.org/packages/powercord-electron-gitl) 

**Additional context**
 - [ YES ] I checked if Discord and/or Powercord are up to date
 - [ YES  ] I made sure this is not related to an external plugin or a theme
 

Full logs:
    ~ ❯ powercord
Hello from Powercord!
Loading Discord
DiscordCanary 0.0.133

(electron:5393): Gtk-WARNING **: 17:07:35.989: Theme parsing error: gtk-widgets.css:1126:11: 'max-height' is not a valid property name
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/kujonello/.config/discordcanary/0.0.133/modules
[Modules] Module installed file path: /home/kujonello/.config/discordcanary/0.0.133/modules/installed.json
[Modules] Module download path: /home/kujonello/.config/discordcanary/0.0.133/modules/pending
file:///usr/lib/discord-canary/app.asar/app_bootstrap/splash/index.html
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/canary/versions.json
[Modules] No module updates available.
Module ./ElectronTestRpc was not included.
https://canary.discord.com/app?_=1645200456555
Uncaught exception:
 TypeError: Cannot read property 'isEncryptionAvailable' of undefined
    at IpcMainImpl.<anonymous> (/home/kujonello/.config/discordcanary/0.0.133/modules/discord_desktop_core/core.asar/app/discord_native/browser/safeStorage.js:12:44)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10307)
    at Object.emit (events.js:315:20)
    at Object.EventEmitter.emit (domain.js:467:12)
TypeError: Cannot read property 'isEncryptionAvailable' of undefined
    at IpcMainImpl.<anonymous> (/home/kujonello/.config/discordcanary/0.0.133/modules/discord_desktop_core/core.asar/app/discord_native/browser/safeStorage.js:12:44)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10307)
    at Object.emit (events.js:315:20)
    at Object.EventEmitter.emit (domain.js:467:12)

**Comment by kujonello79** [comment]
Btw just installed

**Comment by cyyynthia** [comment]
AUR packages are not official, and unsupported by us. The only official means of installing Powercord on Arch is on the `discord-canary` package and via manual install documented at https://powercord.dev/installation.
